// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Open() {
  return window['go']['main']['App']['Open']();
}

export function Save() {
  return window['go']['main']['App']['Save']();
}

export function SendMarkdownToRenderer(arg1) {
  return window['go']['main']['App']['SendMarkdownToRenderer'](arg1);
}
