// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Export():Promise<void>;

export function Open():Promise<main.FileWithContent>;

export function Save():Promise<string>;

export function SendMarkdownToRenderer(arg1:string):Promise<string>;
