name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: write, platform: linux/amd64, os: ubuntu-latest},
          {name: write, platform: windows/amd64, os: windows-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          app-working-directory: write